#####################################################################
#
#Folder where we find the meta and result folders generated by GGIR
baseEpoch="."



##(Re)definiendo variables adaptadas a nuestro proyecto


defineWhat=list(
  nonWear=nonWear,
  isOn=isOn,
  SIB=SIB,
  bed=bedGGIR,
  VIG_01m=function(df)  enmoOver   (df, limInf=400/1000, pctBouts=0.8, durBoutMin=dminutes(1)),
  MVPA_10m=function(df) enmoOver   (df, limInf=100/1000, pctBouts=0.8, durBoutMin=dminutes(10)),
  MVPA_05m=function(df) enmoOver   (df, limInf=100/1000, pctBouts=0.8, durBoutMin=dminutes(5)),
  INAC_20m=function(df) enmoUnder  (df, limSup=40/1000,  pctBouts=0.9, durBoutMin=dminutes(20)),
  LIG_10m=function(df)  enmoBetween(df, limInf=40/1000, limSup=100/1000, pctBouts=0.8, durBoutMin=dminutes(5))
)



#There a la lot of WHEN we want to do the measurements. Some typical are those
defineWhen=function(intervals,idBIN=""){
  bed=genWhen_bedGGIR(intervals,label="bed")
  awake= genWhen_awake(intervals,bed)
  daily=  genWhen_daily(intervals)
  
  list(daily=daily,  
       bed=bed,
       awake=awake
  )
}

  

#Different authos have different criteria validity for some WHENs. Put here your criteria or add new one.
#Please write add the end some text that works as reason to remove that when in computations.
# It will be useful to know whay some data is not going to be used.

whenValidity=list(
  ################################
  #Duration Criteria for validity
  ################################
  directInvalidation=function(summary){
    list(
      invalidBedOfFirstDay(summary,reason="noBedBeforeOn"),
      invalidDuration(summary,whatCond="isOn",whenCond="bed",maxDur=dhours(14),reason="bedTooLong"),
      invalidDuration(summary,whatCond="isOn",whenCond="bed",minDur=dminutes(180),reason="bedTooShort"),
      invalidDuration(summary,whatCond="nonWear",whenCond="daily",maxDur=dminutes(120),reason="nonWear")  
    ) %>% 
      map_df(rbind)
  },
  ##########################
  #Propagation of invalidity
  # If some WHEN is invalid, probably
  # this will affect others. Write it here.
  ##########################
  cascadeInvalid=list(
    daily=c("awake"),
    bed=c("awake")
  )
)



# Perhaps we don not what to measure all WHATS in every WHEN. 
#Put here what your are interested in measuring

whenMeasuresWhat=list(
  "daily"=c("isOn", "nonWear", "MVPA_5m", "MVPA_10m","VIG_01m","INAC_20m","LIG_10m"),
  "awake"=c("isOn","MVPA_5m", "MVPA_10m","VIG_01m","INAC_20m","LIG_10m","SIB"),
  "bed"=c("isOn", "SIB")
)


#The duration of WHAT in WHEN is measured in seconds. If you prefer some other unit, 
#modify it here:
  
durationToUserUnits=function(what,when){
  case_when(
    what == "isOn"      ~ dhours(1),
    what == "SIB" & when=="awake"     ~ dminutes(1),
    what == "SIB"       ~ dhours(1),
    what == "nonWear"   ~ dhours(1), 
    what == "VPA_1m"    ~ dminutes(1), 
    what == "MVPA_5m"   ~ dminutes(1),
    what == "MVPA_10m"  ~ dminutes(1),
    what == "INAC_20m"  ~ dhours(1),
    what == "LIG_10m"  ~ dminutes(1),
    what == "bed"       ~ dhours(1),
    TRUE                ~ dseconds(1)
  )
}

#################################################################
# We create a list with the data needed to execute a project
#################################################################
currentProject=list(
  defineWhat=defineWhat,
  defineWhen=defineWhen,
  whenValidity=whenValidity,
  whenMeasuresWhat=whenMeasuresWhat,
  durationToUserUnits=durationToUserUnits
  )

